### ISSUE TITLE
it seems can't download the dataset correctly, has any other method to download?

### ISSUE THREAD

**Issue by wangwang110** [ekQ/discourse-connectives#1]

**Comment by ekQ** [comment]
Could you provide some more details? You should be able to download the data simply by cloning this repository or directly accessing the files via the web UI: https://raw.githubusercontent.com/ekQ/discourse-connectives/master/connective_examples/discourse_connectives_wikipedia_part0

**Comment by wangwang110** [comment]
sloved the problem  by using git clone 

发自我的iPhone

**Comment by ekQ** [comment]
Good to hear.
